events {}

http {
    # 1. بنعرف شكل الـ Log مرة واحدة بس وبنديله اسم (upstreamlog)
    log_format upstreamlog '[$time_local] $remote_addr - $upstream_addr: $request $status';

    # 2. بنعرف السيرفرات اللي ورا
    upstream myapp {
        server app:80;
    }

    server {
        listen 80;

        # 3. الحتة اللي كانت ناقصة: بنفعل الـ Log باستخدام التنسيق اللي فوق
        access_log /var/log/nginx/access.log upstreamlog;

        location / {
            proxy_pass http://myapp;
            proxy_set_header Host $host;
            add_header X-Served-By $hostname;
        }
    }
}