events {}

http {
    
    log_format upstreamlog '[$time_local] $remote_addr - $upstream_addr: $request $status';


    upstream myapp {
        server app:80;
    }

    server {
        listen 80;

        
        access_log /var/log/nginx/access.log upstreamlog;

        location / {
            proxy_pass http://myapp;
            proxy_set_header Host $host;
            add_header X-Served-By $hostname;
        }
    }
}